ARG ELIXIR_VERSION=1.18.2
ARG OTP_VERSION=27.2.4
ARG DEBIAN_VERSION=bullseye-20250224-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} AS dev

# Install development dependencies
RUN apt-get update -y && apt-get install -y build-essential git inotify-tools \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

# Prepare app directory
WORKDIR /app

# Install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Set development environment
ENV MIX_ENV=dev

COPY . .

RUN mix deps.get && mix deps.compile

# EPMD port for node discovery
EXPOSE 4369

CMD ["elixir", "--sname", "swarmnextjsdev", "--cookie", "test", "-S", "mix", "phx.server"]
