import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :swarm, SwarmWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Swarm.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# https://vercel.com/jon-ators-projects-c14057d4/~/domains/getswarm.dev
config :swarm, frontend_origin: "https://getswarm.dev"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Add to config/prod.exs
# # GITHUB_WEBHOOK_SECRET: ...

# config :instructor,
#   openai: [
#     api_key:
#       ""
#   ]

# config :instructor,
#   anthropic: [
#     api_key:
#       ""
#   ]

# config :langchain,
#   openai_key:
#     ""

# config :langchain,
#        :anthropic_key,
#        ""

# config :swarm, :github_client_id, ""
# config :swarm, :github_client_secret, ""

# config :swarm, :linear_client_id, ""
# config :swarm, :linear_client_secret, ""
# config :swarm, :linear_webhook_secret, ""
# config :swarm, :linear_redirect_uri, "https://getswarm.dev/auth/linear/callback"

# config :swarm,
#        :linear_app_token,
#        ""
